### ISSUE TITLE
"syntax deprecated since version 6.00" in gui.ml, line 89

### ISSUE THREAD

**Issue by GuillaumeBrochu** [geneweb/geneweb#13]
I got this compilation warning-error while trying to compile gui.ml in the geneweb package for Debian
```
cd gui; /usr/bin/make opt
make[3]: Entering directory '/tmp/buildd/geneweb-6.08+git20160228+dfsg/gui'
camlp5r ../wserver/pa_macro5.cmo -DUNIX -o gui.ppo gui.ml
File "gui.ml", line 89, characters 27-34:
Warning: syntax deprecated since version 6.00
```

https://github.com/geneweb/geneweb/blob/distrib-6-08-ocaml-4-xx/gui/gui.ml#L89
https://github.com/geneweb/geneweb/blob/master/gui/gui.ml#L89
(the code is the same for master and for distrib-6-08-ocaml-4-xx)
```
GMain.Io.add_watch chan ~prio:0 ~cond:[`IN; `HUP; `ERR] ~callback:
```

I need an OCAML expert with this one!

**Comment by mbouaziz** [comment]
Apparemment ce n'est pas tout neuf, cf. google "Warning: syntax deprecated since version 6.00"

**Comment by GuillaumeBrochu** [comment]
Est-ce inoffensif? Doit-on corriger?

Je veux juste vérifier que ce n'est pas problématique comme pour les Array.create/Array.make  ou String.create/Bytes.create qui donnaient de tels warnings d'apparence inoffensive mais qui ont complètement brisé la compilation de geneweb pour OCAML >=4.02.

En fait, je ne sais pas trop ce que que fait geneweb-gui au juste, c'est la seule composante qui semble moins bien fonctionner dans mon package d'essai pour Debian. J'essaie seulement de refaire fonctionner ce qui fonctionnait bien avant OCAML 4.02. Mais ça progresse bien, je commence à voir la lumière au bout du tunnel!

**Comment by mbouaziz** [comment]
I am not sure the gui est still used.
This is just a warning (so far at least), emitted by camlp5 (I still don't know why though).
But when I try to compile, I get a real error:
```
File "gui.ml", line 86, characters 13-38:
Error: Unbound module GMain
```
Don't you?

**Comment by GuillaumeBrochu** [comment]
I added this patch to my Debian package prototype to fix this error.

https://github.com/GuillaumeBrochu/geneweb-debian/blob/master/debian/patches/018_gui_makefile_uses_ocamlfind

**Comment by GuillaumeBrochu** [comment]
FYI, I compiled geneweb-gui using pbuilder (and all the Build-Depends installed in the pbuilder base.)

**Comment by mbouaziz** [comment]
Don't hesitate to PR!

Here is the fix for the warning: https://github.com/mbouaziz/geneweb/commit/ea56e2996eec81eb41062694a576f5864b2094f1

**Comment by GuillaumeBrochu** [comment]
Thank you!

Fixing the first error unveils a new error of the same kind in the same file. 

```
camlp5r ../wserver/pa_macro5.cmo -DUNIX -o gui.ppo gui.ml
File "gui.ml", line 93, characters 39-43:
Warning: syntax deprecated since version 6.00
```
https://github.com/mbouaziz/geneweb/blob/master/gui/gui.ml#L93

Actually, this new error had not been reported before the first one was fixed. This let me think that these errors are not inoffensive, as they seem to stop the compilation...

Fortunately, there is only gui.ml that reports warnings of this kind!

**Comment by GuillaumeBrochu** [comment]
Actually, I realized that this file is 1433 lines long... there might be several errors of this kind, since we found two of the at lines 89 and 93...

And to be honest, I've never heard of geneweb-gui before working on the Debian geneweb package. The compilation of this tool doen't seem to be included by default in the current upstream configuration.

And after having read this:
http://www.geneanet.org/forum/?topic=455670.0
and this
http://www.geneanet.org/forum/?topic=454603.0
and this
https://tracker.debian.org/news/358213
perhaps the best solution would be to remove geneweb-gui binary package from geneweb-6-Debian for now?

**Comment by GuillaumeBrochu** [comment]
UPDATE:

Actually, after a few tests, the geneweb-gui seems to compile properly. So these are only inoffensive warnings I think...

I have other errors when executing geneweb-gui, but they don't seem to be related to compilation problem at first sight.

**Comment by GuillaumeBrochu** [comment]
This file should be checked by an OCAML expert.

**Comment by ipfix** [comment]
Why re-open the ticket ? I merged the patch suggested by @mbouaziz it's all fine.

**Comment by GuillaumeBrochu** [comment]
Because there are still warnings...

Using:
https://github.com/GuillaumeBrochu/geneweb/commits/testGUI

Without the last "revert commit",  I get:
`
camlp5r pa_macro.cmo -DUNIX -o gui.ppo gui.ml
File "gui.ml", line 93, characters 39-43:
Warning: syntax deprecated since version 6.00
`

With the last "revert commit",  I get:
`
camlp5r pa_macro.cmo -DUNIX -o gui.ppo gui.ml
File "gui.ml", line 89, characters 27-34:
Warning: syntax deprecated since version 6.00
`

So, the fix is good for line 89, but there is still something to fix on line 93 (and beyond?)

And I guess the makefile could be updated to better manage the compilation of gui ( I had to work a little bit to make it work...)

**Comment by GuillaumeBrochu** [comment]
Anyway, even though there is still a "syntax deprecated" warning on line 93 (and perhaps beyond...), the compiled gui that I obtained with this code seems to work (much better than with the Debian package geneweb-gui). 

So, as mentioned above, these warning are probably inoffensive.

**Comment by GuillaumeBrochu** [comment]
See : https://github.com/geneweb/geneweb/issues/19#issuecomment-210087129

**Comment by GuillaumeBrochu** [comment]
Should be fixed by this commit:

https://github.com/geneweb/geneweb/commit/ceb0f7fee18fd18b925cdcfdf71b71a26ac125fc
