### ISSUE TITLE
gwu "oublie" la raison d'un décès

### ISSUE THREAD

**Issue by hgouraud** [geneweb/geneweb#22]
Le format GW prévoit la possibilité de préciser la raison d’un décès (tué, exécuté, disparu, …)
Il semblerait que gwu ne préserve pas (ou plus) cette information!
<pre>
- h Enf015 1/2/1944 e1/3/1970 					dans le fichier .gw initial
• Exécuté le 1er mars 1970 , à l’âge de 26 ans 		dans la base résultante
• Décédé le 1er mars 1970 , à l’âge de 26 ans 		après gwu - gwc
</pre>
Henri

**Comment by a2line** [comment]
Est-ce que Henri n’oublie pas des choses aussi des fois ?

**Comment by GuillaumeBrochu** [comment]
Voir aussi #2 et #20

**Comment by hgouraud** [comment]
Et pan sur les doigts!
