### ISSUE TITLE
"findlib: [WARNING] Interface diff.cmi occurs in several directories"

### ISSUE THREAD

**Issue by GuillaumeBrochu** [geneweb/geneweb#32]
I guess you have also noticed this compilation warning:
```
findlib: [WARNING] Interface diff.cmi occurs in several directories: 
/home/user/.opam/4.02.3/lib/camlp5, ../../src
```
obtained for more than 10 files.

**Comment by mbouaziz** [comment]
Don't worry, it will be fixed soon when my PR will be merged.
https://github.com/mbouaziz/geneweb/commit/123585800128054c824ff7d3e98c41aee7bab6d0

**Comment by GuillaumeBrochu** [comment]
Should be fixed by this commit:

https://github.com/geneweb/geneweb/commit/bb55942efa66bd898e65be0f790abef2c996dba8
