### ISSUE TITLE
Il faudrait ajouter un tag à la version 6.08-alpha dans le dépôt

### ISSUE THREAD

**Issue by GuillaumeBrochu** [geneweb/geneweb#4]
Il faudrait ajouter un tag à la version 6.08-alpha dans le dépôt, au meilleur de ma connaissance sur ce commit :

https://github.com/geneweb/geneweb/commit/483c73f2191682a78eca7e88f1020b72e4132a08

Comme il existe une différence importante entre la version 6.08-alpha et la version 6.08 et que la version 6.08-alpha s'est retrouvée dans la nature (ex: https://packages.qa.debian.org/g/geneweb.html) sans la mention "alpha", ça serait bien de documenter le tout dans le wiki, car il y a un gros risque de confusion entre les deux versions...

Voir aussi  : https://github.com/geneanet/geneweb/issues/361

**Comment by a2line** [comment]
Et la 7.00alpha aussi.

**Comment by GuillaumeBrochu** [comment]
ATTENTION:

Les binaires ajoutés dimanche soir au tag de la 6.08 sont ceux de la 6.08-alpha... (il suffit d'inspecter le contenu de gw-6.08-linux.tgz pour s'en convaincre...)

https://github.com/geneweb/geneweb/releases/tag/distrib-6-08

Il faudrait donc : 
- ajouter le tag de la 6.08 alpha (voir 1er message ci-haut)
- y attacher les binaires existants pour la 6.08 alpha
- retirer les binaires du tag de la 6.08 finale...

**Comment by GuillaumeBrochu** [comment]
Les binaires attachés à tort au tag "distrib-6-08" ont bien été retirés, c'est donc un début, mais il resterait encore à créer le tag "distrib-6-08-alpha" à partir de ce commit : https://github.com/geneweb/geneweb/commit/483c73f2191682a78eca7e88f1020b72e4132a08, et ce, uniquement dans le but d'être clair pour l'observateur externe quant aux différentes versions en circulation (ce qui n'est pas le cas actuellement). 

Pour la 7.00-alpha, je ne crois pas que ça soit possible de la tagguer proprement dans le dépôt actuel, car elle ne s'insère pas dans le fil actuel de la branche master (qui a été ré-écrit lorsque l'ancienne branche 7.00 a été effacée). Ce n'est pas si grave que ça. On pourrait cependant la générer "artificiellement" à partir des sources publiées en ajoutant un "gros commit" par dessus le tag de la  "distrib-6-08-alpha" qui reste encore à être ajouté, exemple : https://github.com/GuillaumeBrochu/geneweb/commits/Version-7-00-alpha. Mais j'admets que ce n'est pas super élégant de faire ça.

**Comment by ipfix** [comment]
Je ne ferais pas de tag 6.08-alpha ou 7.00-alpha. Il existe un tag 6.08, dont il manque les binaires (je veux bien les faire), mais si la version packagée n'est pas la bonne, c'est au packager de le mettre à jour. De même pour la version 7.00, c'est une version en cours elle n'aura pas de tag alpha. Une version compilée a été distribuée (c'est pour ça qu'il y a la mention alpha), mais le tag ne sera que pour la version stable.

**Comment by GuillaumeBrochu** [comment]
Je suis d'accord que c'est l'erreur du packager d'avoir omis le "-alpha" après le "6.08", mais maintenant que c'est dans la nature... depuis environ 1 an et demi..., ça aurait été préférable de "documenter" le tout dans le dépôt. Après tout, l'émission d'une version "6.08 alpha" fut la décision des développeurs de geneweb à l'origine... Ajouter un tag sur la 6.08 ne coûte rien, ce n'est qu'un outil de communication. Si jamais quelqu'un pose des questions sur "la version 6-08 qui est présente dans Debian sid", c'est plus facile de référer à cette 6.08-alpha avec une référence précise, comme un tag dans le dépôt Github.  Surtout que le commit sur lequel il faudrait mettre le tag 6.08-alpha est directement dans le fil de la branche master, et qu'il n'y a pas de travail supplémentaire à faire pour l'ajouter, à mon avis, ça serait préférable d'en mettre un.

**Comment by GuillaumeBrochu** [comment]
Mais bon, quand j'aurai quelques minutes, je vais signaler officiellement le bug chez Debian pour qu'on remplace la 6.08-alpha mal identifiée par la vraie 6.08.

**Comment by ipfix** [comment]
Le décision de diffuser une version compilée n'a rien à voir avec le fait d'ajouter un tag. N'importe qui peut diffuser une version à partir de n'importe quelle révision. Si on veut faire propre, la seule chose à faire c'est de corriger la version compilée distribuée pour qu'elle corresponde à la bonne révision (supposée 6.08) et pas ajouter un tag pour faire comprendre que c'est pas la version dite finale.

**Comment by GuillaumeBrochu** [comment]
D'accord sur les principes généraux ...

Mais il faut garder à l'esprit que la 6.08 alpha fut appelée ainsi et distribuée à l'époque (sept. 2014) par les développeurs de geneweb eux-mêmes.

http://opensource.geneanet.org/news/10
http://opensource.geneanet.org/attachments/download/254/gw-6.08-alpha-src.tgz

Ce n'est pas une version produite par n'importe qui...

**Comment by ipfix** [comment]
Les développeurs = 1 développeur = moi

**Comment by GuillaumeBrochu** [comment]
Rapporté au mainteneur de package Debian : https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=815528
