### ISSUE TITLE
add checks for piqi and yojson when building api

### ISSUE THREAD

**Issue by a2line** [geneweb/geneweb#48]
Two extra checkings of the presence of the packages piqi and yojson should be added to ./configure --api (like it's done for lablgtk2/curl/redis…).

I add here too that contrary to what configure seems to tell ./configure, lablgtk2 is not necessary to build GeneWeb (with a simple `make`), it's needed only to have the gui (`make all`). Perhaps this can be more clearly shown adding a few more words, for ex.:“ [INFO] Checking Ocaml lablgtk (only needed to build the gui) ........ [OK|NOT FOUND]”.

**Comment by mbouaziz** [comment]
Task assigned to @a2line
