### ISSUE TITLE
gwc2 doesn't work: File "db2out.ml", Assertion failed

### ISSUE THREAD

**Issue by grinapo** [geneweb/geneweb#5]
geneweb v6.08 (debian)

$ gwc2
Uncaught exception: File "db2out.ml", line 138, characters 2-8: Assertion failed

**Comment by ipfix** [comment]
This has been fixed here b5d3121. You should check if your packaged version has this fix (I don't know my self). Or you should build from the source (it's not too complicated).

**Comment by GuillaumeBrochu** [comment]
Grinapo,

This commit (b5d3121) is not in the v6.08 "final" (https://github.com/geneweb/geneweb/releases/tag/distrib-6-08) nor in version 6.08-alpha (the version that is currently in Debian sid). It was applied after, so it is only available in the current development branch (master) for Geneweb 7.00

And beware, I think there is a build dependency problem with the geneweb version that is in Debian sid, please see : https://groups.yahoo.com/neo/groups/geneweb/conversations/messages/6563

**Comment by grinapo** [comment]
Backporting to 6.08 seems to work just fine. I'll notify the maintainer to include it. Thanks. :+1:
