### ISSUE TITLE
Bad behaviour with [ xxx ] strings

### ISSUE THREAD

**Issue by hgouraud** [geneweb/geneweb#53]
My page  calls a file.txt file with m=RSC;v=file command.
file.txt contains jquery calls, in particular
```
...
spots:[
some text containing %sm=IMH other text
] ...
```
In this configuration, the text between square brackets is replaced by .......... (10 periods).
Examination of translate.ml points to a translation behaviour.
Replacing the above by
```
...
spots:[some text containing %sm=IMH other text] 
...
```
has the correct behaviour.

In the second case, I also observe that the %s macro is not processed!! (other instances of %s in file.txt are properly processed).

Although the first problem can be resolved by avoiding placing a newline after the "[", the second problem (%s inside a bracketed text) is a serious limitation!! Macros should be processed before or after translation.

Henri

**Comment by gwmr** [comment]
You can try this:

`...
spots:%[
some text containing %sm=IMH other text
%] ...
...
spots:%[some text containing %sm=IMH other text%] 
...
`

I used it here:
https://github.com/gwmr/geneweb/blob/api/hd/etc/templm/accent.txt#L226

**Comment by hgouraud** [comment]
Excellent!!

merci,
Henri
------
