### ISSUE TITLE
Discussion : should we make a distrib-6-09 to fix compatibility issues with OCAML >=4.02 ?

### ISSUE THREAD

**Issue by GuillaumeBrochu** [geneweb/geneweb#9]
Knowing this bug : https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=815485

I would like to know if it would be possible to produce a 6.09 release of the "old" geneweb, based on release 6.08, with only one main objective : to fix compatibility problems related with OCAML >=4.02 .

All the OCAML >=4.02 fixes for version 7.00 are available in this repository:
https://github.com/geneweb/geneweb/commit/723fb3f9e685646f326de4b41d4017a9624af7c8
https://github.com/geneweb/geneweb/commit/a0d88e917e9204df28f3f67464d1ee012ab6fb49
https://github.com/geneweb/geneweb/commit/86b00d3af835b77c1b7416b22abe3a4a84b9caa5
https://github.com/geneweb/geneweb/commit/b5d312152755b33cafbdba71f233ec02e7205d0e
but these commits would probably need a refactoring for version 6 (more than 65 files are involved). 

Fixing version 6 is probably a quicker solution compared to wait for the final release of version 7.00.

This compilation bug of geneweb in Debian/Ubuntu is "release critical" and could lead Debian package maintainers to remove geneweb from Debian testing.

Any ideas or comments?

**Comment by GuillaumeBrochu** [comment]
Some recent action here : https://github.com/mbouaziz/geneweb/commits/master.4.02

**Comment by ipfix** [comment]
IMHO, I think this issue has nothing to do with geneweb. Nevertheless, there is a problem with the debian package (thanks for filling them a bug report), but it's in the package that the problem is.

To be clear, the ONLY fix is to rebuild the 6.08 tag version with the appropriate OCaml compiler version, i.e. **3.12.1**.

The work you suggest has nothing to do with fixing something. Moreover, the work made by @mbouaziz is already in the master. The verification of the OCaml compiler has been added because it **needs** at least the 4.02 version to build because of a changement in the compiler.

**Comment by GuillaumeBrochu** [comment]
Thank you for these clarifications.

I know that the fix for this compilation bug is already in the master branch for Geneweb 7 (only in THIS repository geneweb/geneweb, not yet in the one of Geneanet...).  It works perfectly with OCAML 4.02, I tested it. 

And I also agree that it's somewhat a Debian problem related to its automatic building of package. The last Debian release that is using OCAML 3.12.1 is the "oldstable" Wheezy : https://packages.debian.org/search?keywords=ocaml. I don't think it's possible to configure Debian to compile the geneweb package with compiler that are not in the same version of Debian (or to configure Debian to use OPAM to compile its packages...), but I will confirm this with the maintainer (C. Perrier). 

[Actually, it would also help if the modifications to the OCAML language were backward compatible, but that's another story...]

For the current discussion, I was more thinking of a "side branch", stored in this repository, starting from https://github.com/geneweb/geneweb/tree/distrib-6-08, for the sole purpose of publishing "official" bug fixes to the "old Geneweb 6", to ease the transition towards the final Geneweb 7 that is not ready yet. As the required fix to backport to version 6 is quite major (more than 65 files involved), it would help to have support from upstream for that task.

I will also try to contact Geneanet maintainers to know what they are doing to solve this problem (actually, I got this answer on the forum : http://www.geneanet.org/forum/?topic=530627.msg1063861#msg1063861)

**Comment by ipfix** [comment]
> And I also agree that it's somewhat a Debian problem related to its automatic building of package. The last Debian release that is using OCAML 3.12.1 is the "oldstable" Wheezy : https://packages.debian.org/search?keywords=ocaml. I don't think it's possible to configure Debian to compile the geneweb package with compiler that are not in the same version of Debian (or to configure Debian to use OPAM to compile its packages...), but I will confirm this with the maintainer (C. Perrier).

Indeed, this is very important to know if it is possible to build geneweb with a previous version of the OCaml compiler. Because if it is not possible, then of course we should consider creating a branch for this sole purpose.

> [Actually, it would also help if the modifications to the OCAML language were backward compatible, but that's another story...]

Yes, I'm not sure about that. They are doing a great job, and the "problem" with the Hashtbl and the string is more our concern. It is our job (developper of geneweb) to maintain the source code in order to work with newer version of the compiler.

> For the current discussion, I was more thinking of a "side branch", stored in this repository, starting from https://github.com/geneweb/geneweb/tree/distrib-6-08, for the sole purpose of publishing "official" bug fixes to the "old Geneweb 6", to ease the transition towards the final Geneweb 7 that is not ready yet. As the required fix to backport to version 6 is quite major (more than 65 files involved), it would help to have support from upstream for that task.

I totally agree for a new branch, but let's wait for an answer about the possibility to build with 3.12. As for the fix, I don't think it's major, it's just about cherry-picking a few commits (5 to be exact)

**Comment by GuillaumeBrochu** [comment]
Perfect.

I will forward this discussion to the Debian geneweb package maintainer (C. Perrier) to get his comments about the requirements for compilation with OCAML in Debian.

**Comment by bubulle** [comment]
For the record, the suggestion of "simply" rebuilding with Ocaml 3.12.1 is....impossible.

There is no Ocaml 3.12.1 in Debian stretch. And software has to be buildable with the tools that are available in the distro, not in old versions of the distro.

So, either geneweb is fixed to compile with Ocaml 4.x....or there won't be any geneweb in Debian strech.....after 16 years of good package maintenance.

**Comment by ipfix** [comment]
Ok, then we can just prepare a dedicated branch with the cherry-picked commit so that Geneweb can be build with the tools provided by Debian.

**Comment by ipfix** [comment]
I just pushed a dedicated branch https://github.com/geneweb/geneweb/tree/distrib-6-08-ocaml-4-xx that has the necessary commit to build with OCaml 4.xx.

**Comment by GuillaumeBrochu** [comment]
Would it be possible to take this opportunity to also push some small bugs fixes related to 
-minor template bugs that I identified few months ago
-copyright date update
-others

Example :
https://github.com/GuillaumeBrochu/geneweb/commit/05d935f52eb053ffde28d07111eb9df75884deac
https://github.com/a2line/geneweb/commit/d57d2c7beeb9d47643fa310987500865efa84ebf
https://github.com/GuillaumeBrochu/geneweb/commit/05c4dff9af7aea47afb4360a2f837ca105727cc7
https://github.com/geneweb/geneweb/commit/583f5b451472323df9e70c9e700e7ac1db9c8368
https://github.com/geneweb/geneweb/commit/a6e8f781ede3df81ac67b11dc0f1a7c17b2ff1d9
https://github.com/geneweb/geneweb/commit/5866720b03c649f21bda8e286ec7a9559ae3ccc3


I could prepare a PR tonight for these minor bugs, if this is required. Ipfix, let me know what do you think about this.

**Comment by ipfix** [comment]
Well, it's not that I'm against it, but, I would rather see this branch just with the necessary fix to build Geneweb. If we add the few fix you suggest, then there is no good reason not to add the other fixes that are in the master branch.

**Comment by GuillaumeBrochu** [comment]
That's a delicate question indeed.

My motivation for these other minor fixes (these are just fixes, not new features) is to provide a better experience to geneweb users on Debian by solving bugs that were annoying to me (reported about one year ago on the Geneanet repo...) , and other minor stuff (Copyright date, broken makefile links for separate tools, etc). And there is an opportunity window to fix them now.

But if you prefer to not open the "Pandora box" of more bug fixes, so let's finish this right now. The main objective is to keep geneweb in Debian testing.

**Comment by GuillaumeBrochu** [comment]
I compiled the code at the top of the new branch with OPAM/OCAML4.02.3.

Everything seems to work fine, no compilation errors or fatal warnings, no weird user bugs like those described here :  https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=815485

:+1:

**Comment by a2line** [comment]
I don't understand all this, if it's Debian testing, why don't they test
Geneweb 7 that is Ocaml4.xx compliant?!

– A2

2016-02-28 3:55 GMT+01:00 Guillaume Brochu <notifications@github.com>:

**Comment by GuillaumeBrochu** [comment]
"Testing" in Debian means testing the integration of "quite" stable software in preparation for the next major Debian release (Stretch). In my opinion, since there is still intense development in geneweb 7 (gwc2 not working, improving events and gwplus file format, #nsck that are not surviving import/export cycles, H trees still to be added, etc.), the right place for geneweb 7 would be the experimental repository.
https://wiki.debian.org/DebianExperimental
https://www.debian.org/releases/

The schedule for the next Debian release is here:
https://wiki.debian.org/DebianStretch
If we want to push Geneweb 7 in Debian Testing(Stretch), we have to complete the work by next fall.

As Christian Perrier told me, the typical user of geneweb in Debian currently is looking more for stability than new features. It's not the time to push them a version that is not finalized and that is not 100% usable for genealogy work. People that want to test new features will find us on Github!

**Comment by bubulle** [comment]
Perfect explanation by Guillaume. People who fail to understand what stability means for Debian, fail to understand what Debian is about...:-)

It is way too early to adopt GW 7.0 in a stable distro. From what I have understood the process for migrating databases is kinda cumbersome nd will probably be hard to automate in an upgrade script (yes, we'll have to deal with that : a distro is not only dropping new binaries in /usr/bin....).

Geneweb 7.x will be for the next release of Debian if it happens some day (GW 7, not the next release of Debian)

**Comment by ipfix** [comment]
> From what I have understood the process for migrating databases is kinda cumbersome nd will probably be hard to automate in an upgrade script (yes, we'll have to deal with that : a distro is not only dropping new binaries in /usr/bin....).

Well the migration process is exactly:
1/ export database with previous version
2/ import database with new version

**Comment by ipfix** [comment]
Since geneweb database v7.00 are incompatible with previous version, a message will be displayed to say the database has to be updated (through the process export/import).

The problem is how do we provide the necessary previous tool for that export. I can't answer the problem now, but this is off topic for this issue, it will be a concern when 7.00 is ready to go.

**Comment by GuillaumeBrochu** [comment]
For Debian/Ubuntu, a possible solution would be to provide TWO geneweb packages for a given period of time (corresponding to one Debian stable release...). These two packages would not be allowed to be installed at the same time. For example, "geneweb" for the good old geneweb 6 and geneweb7 for the new improved version with events and other new features (and the same recipe would be applied for gwsetup, geneweb-gui and gwtp, https://packages.debian.org/fr/source/sid/geneweb).

This way, the automatic migration with dist-upgrade will not break databases as geneweb 6 will continue to be used by default, and users will have time to plan their deliberate migration to geneweb 7.

**Comment by bubulle** [comment]
I did this with samba and it turned out to be a very bad idea. No, really, the point is that databases have to be migrated when the software is upgraded. But this has to be done automatically through maintainer scripts. Indeed, there is, IIRC, some very old codes still lying in the maintainer scripts, as we had to do this already once in the past (around 2000, IIRC).

What we *can't* do is just upgrading the software and leave it up to users to migrate their databases.

**Comment by GuillaumeBrochu** [comment]
La nouvelle version 6.08+git20160228+dfsg-1 est maintenant dans Debian Sid et dans le "pre-release freeze" de Ubuntu 16.04 LTS! Elle devrait aussi arriver dans Debian testing d'ici quelques jours.

https://packages.qa.debian.org/g/geneweb.html
https://launchpad.net/ubuntu/+source/geneweb

Merci a tous!
